import { DateOnly, Entity, EntityProps, Id, Money, Result } from '@poupig/shared';
import {
  Direction,
  isDirection,
  isTransactionStatus,
  MovementErrors,
  MovementName,
  MovementNote,
  TransactionStatus,
} from '../../movement';

export interface ScheduledTransactionProps extends EntityProps {
  userId: string;
  seriesId: string;
  /** Position of the occurrence inside its series, base 0. */
  occurrenceIndex: number;
  /** Date the series calculated for the occurrence. Never edited by the user. */
  occurrenceOn: string;
  name: string;
  note?: string | null;
  value: number;
  direction: Direction;
  accountId: string;
  creditCardId?: string | null;
  subcategoryId?: string | null;
  status?: TransactionStatus;
  /** Date the user sees and may move, before or after `occurrenceOn`. */
  expectedOn: string;
  settledOn?: string | null;
}

export const ScheduledTransactionErrors = {
  SCHEDULED_TRANSACTION_NOT_FOUND: 'SCHEDULED_TRANSACTION_NOT_FOUND',
  SCHEDULED_TRANSACTION_SETTLED_ON_REQUIRED: 'SCHEDULED_TRANSACTION_SETTLED_ON_REQUIRED',
  INVALID_SCHEDULED_TRANSACTION_SERIES_ID: 'INVALID_SCHEDULED_TRANSACTION_SERIES_ID',
  INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_INDEX: 'INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_INDEX',
  INVALID_SCHEDULED_TRANSACTION_ACCOUNT_ID: 'INVALID_SCHEDULED_TRANSACTION_ACCOUNT_ID',
  INVALID_SCHEDULED_TRANSACTION_CREDIT_CARD_ID: 'INVALID_SCHEDULED_TRANSACTION_CREDIT_CARD_ID',
  INVALID_SCHEDULED_TRANSACTION_SUBCATEGORY_ID: 'INVALID_SCHEDULED_TRANSACTION_SUBCATEGORY_ID',
  INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_ON: 'INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_ON',
  INVALID_SCHEDULED_TRANSACTION_EXPECTED_ON: 'INVALID_SCHEDULED_TRANSACTION_EXPECTED_ON',
  INVALID_SCHEDULED_TRANSACTION_SETTLED_ON: 'INVALID_SCHEDULED_TRANSACTION_SETTLED_ON',
} as const;

/** A base 0 occurrence index: `PositiveInteger` is not used because it rejects 0. */
function isOccurrenceIndex(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value >= 0;
}

/**
 * One occurrence generated by a transaction series. Its business identity is
 * the pair `(seriesId, occurrenceIndex)`: at most one occurrence is stored per
 * pair. A stored occurrence is an override of the user over the series, so
 * there is no soft delete — reverting it removes the record.
 */
export class ScheduledTransaction extends Entity<ScheduledTransaction, ScheduledTransactionProps> {
  private constructor(props: ScheduledTransactionProps) {
    super(props);
  }

  static create(props: ScheduledTransactionProps): ScheduledTransaction {
    const result = ScheduledTransaction.tryCreate(props);
    result.validator.throwsIfFailed();
    return result.instance;
  }

  static tryCreate(props: ScheduledTransactionProps): Result<ScheduledTransaction> {
    const id = Id.tryCreate(props.id);
    const userId = Id.tryCreate(props.userId, { attribute: 'userId' });
    const name = MovementName.tryCreate(props.name);
    const value = Money.tryCreate(props.value);
    // `Id` generates a new uuid for an empty value, so a missing series or account must be rejected before it.
    const seriesId = props.seriesId ? Id.tryCreate(props.seriesId, { attribute: 'seriesId' }) : undefined;
    const accountId = props.accountId ? Id.tryCreate(props.accountId, { attribute: 'accountId' }) : undefined;
    const occurrenceOn = DateOnly.tryCreate(props.occurrenceOn);
    const expectedOn = DateOnly.tryCreate(props.expectedOn);
    const status = props.status ?? TransactionStatus.PENDING;

    const results: Result<unknown>[] = [id, userId, name, value];

    if (!isDirection(props.direction)) {
      results.push(Result.fail(MovementErrors.INVALID_DIRECTION));
    }

    if (!isTransactionStatus(status)) {
      results.push(Result.fail(MovementErrors.INVALID_TRANSACTION_STATUS));
    }

    if (!seriesId || seriesId.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_SERIES_ID));
    }

    if (!isOccurrenceIndex(props.occurrenceIndex)) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_INDEX));
    }

    if (occurrenceOn.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_OCCURRENCE_ON));
    }

    if (expectedOn.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_EXPECTED_ON));
    }

    if (!accountId || accountId.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_ACCOUNT_ID));
    }

    const note = props.note ? MovementNote.tryCreate(props.note) : undefined;
    if (note) {
      results.push(note);
    }

    const creditCardId = props.creditCardId
      ? Id.tryCreate(props.creditCardId, { attribute: 'creditCardId' })
      : undefined;
    if (creditCardId?.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_CREDIT_CARD_ID));
    }

    const subcategoryId = props.subcategoryId
      ? Id.tryCreate(props.subcategoryId, { attribute: 'subcategoryId' })
      : undefined;
    if (subcategoryId?.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_SUBCATEGORY_ID));
    }

    const settledOn = props.settledOn ? DateOnly.tryCreate(props.settledOn) : undefined;
    if (settledOn?.isFailure) {
      results.push(Result.fail(ScheduledTransactionErrors.INVALID_SCHEDULED_TRANSACTION_SETTLED_ON));
    }

    const combined = Result.combine(results);
    if (combined.isFailure) return Result.fail(combined.errors!);

    // Only now the invariant that depends on more than one attribute.
    if (status === TransactionStatus.SETTLED && !settledOn) {
      return Result.fail(ScheduledTransactionErrors.SCHEDULED_TRANSACTION_SETTLED_ON_REQUIRED);
    }

    return Result.ok(
      new ScheduledTransaction({
        ...props,
        id: id.instance.value,
        userId: userId.instance.value,
        seriesId: seriesId!.instance.value,
        occurrenceIndex: props.occurrenceIndex,
        occurrenceOn: occurrenceOn.instance.value,
        name: name.instance.value,
        note: note ? note.instance.value : null,
        value: value.instance.value,
        direction: props.direction,
        accountId: accountId!.instance.value,
        creditCardId: creditCardId ? creditCardId.instance.value : null,
        subcategoryId: subcategoryId ? subcategoryId.instance.value : null,
        status,
        expectedOn: expectedOn.instance.value,
        // Only a settled occurrence keeps its settlement date.
        settledOn: status === TransactionStatus.SETTLED && settledOn ? settledOn.instance.value : null,
        // Never soft deleted: a stored occurrence is removed physically.
        deletedAt: null,
      }),
    );
  }

  get userId(): string {
    return this.props.userId;
  }

  get seriesId(): string {
    return this.props.seriesId;
  }

  get occurrenceIndex(): number {
    return this.props.occurrenceIndex;
  }

  get occurrenceOn(): string {
    return this.props.occurrenceOn;
  }

  get name(): string {
    return this.props.name;
  }

  get note(): string | null {
    return this.props.note ?? null;
  }

  get value(): number {
    return this.props.value;
  }

  get direction(): Direction {
    return this.props.direction;
  }

  get accountId(): string {
    return this.props.accountId;
  }

  get creditCardId(): string | null {
    return this.props.creditCardId ?? null;
  }

  get subcategoryId(): string | null {
    return this.props.subcategoryId ?? null;
  }

  get status(): TransactionStatus {
    return this.props.status ?? TransactionStatus.PENDING;
  }

  get expectedOn(): string {
    return this.props.expectedOn;
  }

  get settledOn(): string | null {
    return this.props.settledOn ?? null;
  }
}
