export const DevDataErrors = {
  INVALID_DEV_DATA_REQUEST: 'INVALID_DEV_DATA_REQUEST',
  INVALID_DEV_DATA_QUANTITY: 'INVALID_DEV_DATA_QUANTITY',
  INVALID_DEV_DATA_PERIOD: 'INVALID_DEV_DATA_PERIOD',
  INVALID_DEV_DATA_SEED: 'INVALID_DEV_DATA_SEED',
  DEV_DATA_ACCOUNT_REQUIRED: 'DEV_DATA_ACCOUNT_REQUIRED',
  DEV_DATA_DISABLED: 'DEV_DATA_DISABLED',
} as const;
