services:
  postgres:
    image: postgres:16-alpine
    container_name: poupig-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: poupig
      POSTGRES_PASSWORD: poupig
      POSTGRES_DB: poupig
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U poupig']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
